provasonline/aluno/controller.py
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, request

aluno = Blueprint('aluno', __name__, template_folder='templates')

@aluno.route("/listar_alunos", methods=["GET","POST"])
def listar_alunos():
    return render_template("listar_alunos.html")

provasonline/turma/controller.py
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, request

turma = Blueprint('turma', __name__, template_folder='templates')

@turma.route("/listar_turmas", methods=["GET","POST"])
def listar_turmas():
    return render_template("listar_turmas.html")

provasonline/templates/base.html
<!doctype html>
<html lang="pt-br">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

        <title>{% block title %} Provas Online {% endblock %}</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{url_for('usuario.index')}}">PROVAS ONLINE</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link {{ 'active' if active_page == 'home' else '' }}" href="{{url_for('usuario.index')}}">Home</a>
                  <a class="nav-link {{ 'active' if active_page == 'alunos' else '' }}" href="{{url_for('aluno.listar_alunos')}}">Alunos</a>
                  <a class="nav-link {{ 'active' if active_page == 'turmas' else '' }}" href="{{url_for('turma.listar_turmas')}}">Turmas</a>
                  <a class="nav-link {{ 'active' if active_page == 'provas' else '' }}" href="{{url_for('prova.listar_provas')}}">Provas</a>
                  <a class="nav-link" href="#">Logout</a>
                </div>
              </div>
            </div>
        </nav>
        
        <br><br>

        <div class="container">
          <!-- Flashed Messages Start -->
          {% with messages = get_flashed_messages() %} {% if messages %}
          <div>
            {% for message in messages %}
            <p>
              <b>{{ message }}</b>
            </p>
            {% endfor %}
          </div>
          <br />
          <br>
          {% endif %} {% endwith %}
          <!-- Flashed Messages End -->                
        </div>

        {% block content %}
        {% endblock %}

        <br><br> 

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body> 
</html>