provasonline/prova/models/Prova.py
from provasonline import db

class Prova(db.Model):

    __tablename__ = 'prova'
    id          = db.Column(db.Integer, primary_key = True)
    descricao   = db.Column(db.Text, nullable = True)
    data        = db.Column(db.Date, nullable = False)
    valor       = db.Column(db.Integer, nullable = True)
    professor   = db.Column(db.Integer, db.ForeignKey('professor.id', ondelete = 'CASCADE'), nullable = True)

    perguntas = db.relationship("Pergunta", backref='perguntas', lazy='dynamic')
    
    def __init__(self, data, descricao, valor, professor):
        self.data      = data
        self.descricao = descricao
        self.valor     = valor
        self.professor = professor

class Pergunta(db.Model):

    __tablename__ = 'pergunta'
    id          = db.Column(db.Integer, primary_key = True)
    descricao   = db.Column(db.Text, nullable = False)
    prova       = db.Column(db.Integer, db.ForeignKey('prova.id', ondelete = 'CASCADE'), nullable = False)
    valor       = db.Column(db.Integer, nullable = True)

    opcoes = db.relationship("Opcao", backref='opcoes', lazy='dynamic')
    
    def __init__(self, descricao, prova, valor):
        self.descricao = descricao
        self.prova     = prova
        self.valor     = valor

class Opcao(db.Model):

    __tablename__ = 'opcao'
    id          = db.Column(db.Integer, primary_key = True)
    descricao   = db.Column(db.Text, nullable = False)
    correta     = db.Column(db.Boolean, nullable = True)
    pergunta    = db.Column(db.Integer, db.ForeignKey('pergunta.id', ondelete = 'CASCADE'), nullable = False)
    
    def __init__(self, descricao, correta, pergunta):
        self.descricao = descricao
        self.correta   = correta
        self.pergunta  = pergunta

class Resposta(db.Model):

    __tablename__ = 'resposta'
    id         = db.Column(db.Integer, primary_key = True)
    prova      = db.Column(db.Integer, db.ForeignKey('prova.id', ondelete = 'CASCADE'), nullable = False)
    pergunta   = db.Column(db.Integer, db.ForeignKey('pergunta.id', ondelete = 'CASCADE'), nullable = False)
    opcao      = db.Column(db.Integer, db.ForeignKey('opcao.id', ondelete = 'CASCADE'), nullable = False)
    acertou    = db.Column(db.Boolean, nullable = True)
    aluno      = db.Column(db.Integer, db.ForeignKey('aluno.id', ondelete = 'CASCADE'), nullable = True)

    pergunta_obj = db.relationship('Pergunta', foreign_keys=pergunta)
    prova_obj    = db.relationship('Prova', foreign_keys=prova)
    opcao_obj    = db.relationship('Opcao', foreign_keys=opcao)
    
    def __init__(self, prova, pergunta, opcao, acertou, aluno):
        self.prova    = prova
        self.pergunta = pergunta
        self.opcao    = opcao
        self.acertou  = acertou
        self.aluno    = aluno

provasonline/prova/controller.py
from provasonline import db, login_required
from provasonline.prova.models.Prova import Opcao, Pergunta, Prova, Resposta
from provasonline.constants import usuario_urole_roles
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, request
from datetime import datetime, date

prova = Blueprint('prova', __name__, template_folder='templates')

@prova.route("/cadastrar_prova", methods=["GET","POST"])
# @login_required(role=[usuario_urole_roles['PROFESSOR']])
def cadastrar_prova():
    valor_total = 0

    if request.method == 'POST':

        descricao = request.form['prova']
        data      = datetime.strptime(request.form['data'], '%Y-%m-%d').date()
        #TODO: professor como current_user (preciso do login pronto)
        prova     = Prova(data, descricao, 0, 9)
        db.session.add(prova)
        db.session.commit()

        numero_de_perguntas = request.form['numero_de_perguntas']

        contador = 0

        while (contador < int(numero_de_perguntas)):    
            pergunta = request.form['pergunta'+str(contador)] 
            valor    = request.form['valor'+str(contador)] 

            valor_total = valor_total + int(valor)
            
            questao = Pergunta(pergunta, prova.id, valor)
            db.session.add(questao)    
            db.session.commit()

            opcao1   = request.form['opcao'+str(contador)+'1']
            opcao2   = request.form['opcao'+str(contador)+'2']
            opcao3   = request.form['opcao'+str(contador)+'3']
            opcao4   = request.form['opcao'+str(contador)+'4']   

            correta  = int(request.form['correta'+str(contador)])
            
            alternativa1 = Opcao(opcao1, False, questao.id)
            alternativa2 = Opcao(opcao2, False, questao.id)
            alternativa3 = Opcao(opcao3, False, questao.id)
            alternativa4 = Opcao(opcao4, False, questao.id)

            if (correta == 1):
                alternativa1.correta = True
            elif (correta == 2):
                alternativa2.correta = True
            elif (correta == 3):
                alternativa3.correta = True
            else:        
                alternativa4.correta = True

            db.session.add(alternativa1)
            db.session.add(alternativa2)
            db.session.add(alternativa3)
            db.session.add(alternativa4)                   

            contador = contador + 1    

        prova.valor = valor_total
        
        db.session.commit() 
        flash("Prova cadastrada com sucesso")
        return redirect(url_for('prova.listar_provas'))    

    return render_template("cadastrar_prova.html")

@prova.route("/listar_provas", methods=["GET","POST"])
# @login_required()
def listar_provas():
    #TODO: listar provas do current_user
    #TODO: separar tipo de listagem de aluno e professor

    provas = Prova.query.all()
    return render_template("listar_provas.html", provas = provas)

@prova.route("/responder_prova/<_id>", methods=["GET","POST"])
# @login_required()
def responder_prova(_id):
    prova = Prova.query.get_or_404(_id) 

    #TODO: se ja tiver essa prova respondida pra esse aluno, bloqueia
    #TODO: aluno como current_user (preciso do login pronto)
    #TODO: remover a permissão do botão para o professor

    if request.method == 'POST':
        for p in prova.perguntas: 
            opcao = request.form['op'+str(p.id)]
            
            aux = Opcao.query.get_or_404(opcao)

            if (aux.correta == 1):                
                resposta = Resposta(_id, p.id, opcao, 1, 8)
            else:
                resposta = Resposta(_id, p.id, opcao, 0, 8)

            db.session.add(resposta)    
        db.session.commit()    

        flash("Prova respondida com sucesso!")
        return redirect(url_for('prova.prova_respondida', _id = _id))  

    return render_template("responder_prova.html", prova = prova)

@prova.route("/prova_respondida/<_id>", methods=["GET","POST"])
# @login_required()
def prova_respondida(_id):
    prova = Prova.query.get_or_404(_id)
    respostas = Resposta.query.filter(Resposta.prova == _id).all()
    return render_template("prova_respondida.html", prova = prova, respostas = respostas)

provasonline/prova/routes.py
from flask import Blueprint

prova = Blueprint('prova', __name__, template_folder='templates')

provasonline/prova/templates/cadastrar_prova.html
{% extends "base.html" %}
{% set active_page = "provas" %}
{% block title %}Criar Prova{% endblock %}

{% block content %}

<form action="" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <div class="container">

        <div class="row g-3 mb-5">
            <div class="col-md-8">
                <label for="prova" class="form-label">Descrição:</label>
                <input type="text" class="form-control" id="prova" name="prova" required>
            </div>
            <div class="col-md-4">
                <label for="data" class="form-label">Data:</label>
                <input type="date" class="form-control" id="data" name="data" required>
            </div>
        </div>

        <div class="row g-3 mb-3">
            <div class="col-md-10 ">
                <label for="pergunta" class="form-label">Pergunta 1:</label>
                <input type="text" class="form-control" id="pergunta" name="pergunta0" required>
            </div>
          
            <div class="col-md-2">
                <label for="valor" class="form-label">Valor:</label>
                <input type="number" min="0" class="form-control" id="valor" name="valor0" required>
            </div>     
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Opção 1</span>
            <input type="text" class="form-control" id="opcao1" name="opcao01" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
            
            <div class="input-group-text">
                <input class="form-check-input mt-0" type="radio" value="1" id="radio1" name="correta0" required>
            </div>        
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Opção 2</span>
            <input type="text" class="form-control" id="opcao2" name="opcao02" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
            
            <div class="input-group-text">
                <input class="form-check-input mt-0" type="radio" value="2" id="radio2" name="correta0" required>
            </div> 
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Opção 3</span>
            <input type="text" class="form-control" id="opcao3" name="opcao03" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
            
            <div class="input-group-text">
                <input class="form-check-input mt-0" type="radio" value="3" id="radio3" name="correta0" required>
            </div> 
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Opção 4</span>
            <input type="text" class="form-control" id="opcao4" name="opcao04" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
            
            <div class="input-group-text">
                <input class="form-check-input mt-0" type="radio" value="4" id="radio4" name="correta0" required>
            </div> 
        </div>

        <div id="saida"></div>

        <div class="d-flex justify-content-between">
            <a class="btn btn-primary" id="add_quest">Adicionar</a>
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </div>    

    <input type="hidden" id="numero_de_perguntas" name="numero_de_perguntas" value="1" />
    <input type="hidden" id="valor_total" name="valor_total" value="1" />
</form>

<template id="templateLinha">
    <br>
    <div class="row g-3 mb-3">
        <div class="col-md-10 ">
            <label for="pergunta" class="form-label">Pergunta</label>
            <input type="text" class="form-control" id="pergunta" required>
        </div>
      
        <div class="col-md-2">
            <label for="valor" class="form-label">Valor:</label>
            <input type="number" min="0" class="form-control" id="valor" required>
        </div>     
    </div>

    <div class="input-group mb-3">
        <span class="input-group-text" id="inputGroup-sizing-default">Opção 1</span>
        <input type="text" class="form-control" id="opcao1" name="opcao01" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
        
        <div class="input-group-text">
            <input class="form-check-input mt-0" type="radio" value="1" id="radio1" name="correta0" required>
        </div>        
    </div>

    <div class="input-group mb-3">
        <span class="input-group-text" id="inputGroup-sizing-default">Opção 2</span>
        <input type="text" class="form-control" id="opcao2" name="opcao02" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
        
        <div class="input-group-text">
            <input class="form-check-input mt-0" type="radio" value="2" id="radio2" name="correta0" required>
        </div> 
    </div>

    <div class="input-group mb-3">
        <span class="input-group-text" id="inputGroup-sizing-default">Opção 3</span>
        <input type="text" class="form-control" id="opcao3" name="opcao03" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
        
        <div class="input-group-text">
            <input class="form-check-input mt-0" type="radio" value="3" id="radio3" name="correta0" required>
        </div> 
    </div>

    <div class="input-group mb-3">
        <span class="input-group-text" id="inputGroup-sizing-default">Opção 4</span>
        <input type="text" class="form-control" id="opcao4" name="opcao04" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" required>
        
        <div class="input-group-text">
            <input class="form-check-input mt-0" type="radio" value="4" id="radio4" name="correta0" required>
        </div> 
    </div>
</template>

<script>
    let cont = 1;
    document.getElementById("add_quest").onclick = function clone() {
        let container = document.getElementById("saida");  
        let tempLinha = document.querySelector('#templateLinha');
        let clone = document.importNode(tempLinha.content, true); 
        var numero_de_perguntas = document.getElementById("numero_de_perguntas");
        
        const label = clone.querySelector("label");
        label.textContent = "Pergunta " + (cont+1) + ": ";
        clone.querySelector("#pergunta").name = "pergunta" + cont;
        clone.querySelector("#valor").name = "valor" + cont;

        clone.querySelector("#opcao1").name = "opcao" + cont + 1;
        clone.querySelector("#opcao2").name = "opcao" + cont + 2;
        clone.querySelector("#opcao3").name = "opcao" + cont + 3;
        clone.querySelector("#opcao4").name = "opcao" + cont + 4;

        clone.querySelector("#radio1").name = "correta" + cont;
        clone.querySelector("#radio2").name = "correta" + cont;
        clone.querySelector("#radio3").name = "correta" + cont;
        clone.querySelector("#radio4").name = "correta" + cont;

        var radios = document.getElementsByName('correta'+cont);
        radios.required = this.checked;
        
        container.appendChild(clone);
        cont++;

        numero_de_perguntas.value = cont;
    }
</script>

{% endblock %}

provasonline/prova/templates/editar_prova.html
{% extends "base.html" %}

{% block content %}

editar prova

{% endblock %}

provasonline/prova/templates/listar_provas.html
{% extends "base.html" %}
{% set active_page = "provas" %}
{% block title %}Provas{% endblock %}

{% block content %}

<div class="container">
    <div class="d-flex justify-content-end mb-2">
        <a href="{{url_for('prova.cadastrar_prova')}}" type="button" class="btn btn-primary" role="button">Nova Prova</a>
    </div>
    

    {% for prova in provas %} 
    <a href="{{url_for('prova.responder_prova', _id = prova.id)}}" type="button" class="btn btn-outline-secondary col-md-12 mb-2" role="button">
        <div class="d-flex justify-content-start">
            {{ prova.descricao }} 
        </div>
        <div class="d-flex justify-content-end">
            {{ prova.data }}
        </div>
    </a>
    {% endfor %}

</div>

{% endblock %}

provasonline/prova/templates/prova_corrigida.html
{% extends "base.html" %}

{% block content %}

PROVA CORRIGIDA

{% endblock %}

provasonline/prova/templates/prova_respondida.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="mb-4">
            <h4>{{ prova.descricao }}</h4>
        </div>

        <script>cont = 1;</script>

        {% for resposta in respostas %}
        <div class="card mb-3">
            <div class="card-header" id="teste{{ resposta.pergunta }}">
                <script>document.getElementById("teste{{ resposta.pergunta }}").innerHTML="Questão "+cont;</script>
            </div>
            
            <div class="card-body">               
                <p class="card-text">{{ resposta.pergunta_obj.descricao }}</p>
                
                {% for opcao in resposta.pergunta_obj.opcoes %}
                <div class="input-group mb-3">
                    <div class="input-group-text">
                        {% if resposta.opcao == opcao.id %}
                        <input class="form-check-input mt-0" type="radio" name="op{{ resposta.pergunta_obj.id }}" value="{{ opcao.id }}" checked disabled>
                        {% else %}
                        <input class="form-check-input mt-0" type="radio" name="op{{ resposta.pergunta_obj.id }}" value="{{ opcao.id }}" disabled>
                        {% endif %}
                    </div>
                    <input type="text" class="form-control" value="{{ opcao.descricao }}" disabled>                    
                </div>
                {% endfor %}                
            </div>
        </div>

        <script>cont++;</script>  
        {% endfor %}
    </div>    

{% endblock %}

provasonline/prova/templates/responder_prova.html
{% extends "base.html" %}

{% block content %}

<form action="" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <div class="container">
        <div class="mb-4">
            <h4>{{ prova.descricao }}</h4>
        </div>

        <script>cont = 1;</script>

        {% for pergunta in prova.perguntas %}
        <div class="card mb-3">
            <div class="card-header" id="teste{{ pergunta.id }}">
                <script>document.getElementById("teste{{ pergunta.id }}").innerHTML="Questão "+cont;</script>
            </div>
            
            <div class="card-body">               
                <p class="card-text">{{ pergunta.descricao }}</p>
                
                {% for opcao in pergunta.opcoes %}
                <div class="input-group mb-3">
                    <div class="input-group-text">
                        <input class="form-check-input mt-0" type="radio" name="op{{ pergunta.id }}" value="{{ opcao.id }}" required>
                    </div>
                    <input type="text" class="form-control" value="{{ opcao.descricao }}" disabled>                    
                </div>
                {% endfor %}                
            </div>
        </div>

        <script>cont++;</script>  
        {% endfor %}

        <div class="d-flex justify-content-end">    
            <button type="submit" class="btn btn-success">Enviar</button>
        </div>
    </div>    

</form>

{% endblock %}